steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/demo-k8s-secrets:$REVISION_ID", "."]
  dir: 'demo-k8s-secrets'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/demo-k8s-secrets:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--filename=k8s-manifests/demo-k8s-secrets-deployment.yaml'
  - '--image=gcr.io/$PROJECT_ID/demo-k8s-secrets:$REVISION_ID'
  - '--location=us-central1-a'
  - '--cluster=niran-poc-cluster'
  - '--namespace=ns-niran-poc'
images: ['gcr.io/$PROJECT_ID/demo-k8s-secrets:$REVISION_ID']
