steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/demo-frontend-spring-mvc:$REVISION_ID", "."]
    dir: 'demo-frontend-spring-mvc'
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/demo-frontend-spring-mvc:$REVISION_ID"]
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
      - 'run'
      - '--filename=k8s-manifests/rfi-backend-api-deployment.yaml'
      - '--image=gcr.io/$PROJECT_ID/rfi-backend:$REVISION_ID'
      - '--location=us-central1-a'
      - '--cluster=niran-rfi-poc-cluster'
      - '--namespace=rfi-niran'
images: ['gcr.io/$PROJECT_ID/rfi-backend:$REVISION_ID']
