runtime: python27
api_version: 1
threadsafe: true
service: niran

handlers:
- url: /robots.txt
  static_files: www/robots.txt
  upload: www/robots.txt

# file with extensions (longer cache period)
- url: /(.*\.(css|js|woff|woff2|ico|png|jpg))
  static_files: www/\1
  upload: www/(.*)
  expiration: "14d"

# file with extensions
- url: /(.*\..*)
  static_files: www/\1
  upload: www/(.*)

# assume file without extensions use index.html
- url: /(.*)/
  static_files: www/\1/index.html
  upload: www/(.*)/index.html

- url: /
  static_files: www/index.html
  upload: www/index.html