apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-secrets
  namespace: rfi-niran
  labels:
    app: demo-k8s-secrets
    owner: niran
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-k8s-secrets
      owner: niran
  template:
    metadata:
      labels:
        app: demo-k8s-secrets
        owner: niran
    spec:
      containers:
      - name: demo-k8s-secrets-container
        image: gcr.io/opportune-mile-246823/demo-k8s-secrets
        env:
        - name: SECRETS_DEMO_USER
          valueFrom:
            secretKeyRef:
              name: demo-k8s-secret
              key: spring.user.name
        - name: SECRETS_DEMO_PASS
          valueFrom:
            secretKeyRef:
              name: demo-k8s-secret
              key: spring.user.password
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/liveness
        #     port: 8080
        #   initialDelaySeconds: 20
        #   timeoutSeconds: 10
        #   failureThreshold: 10