apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-configmap-as-file-service
  #namespace: rfi-niran
  labels:
    app: demo-k8s-configmap-as-file
    owner: niran
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: demo-k8s-configmap-as-file
    owner: niran
  type: LoadBalancer
  loadBalancerIP: 
