runtime: python27
api_version: 1
threadsafe: true
service: funlokam

handlers:
- url: /robots.txt
  static_files: www/robots.txt
  upload: www/robots.txt
  secure: always
  redirect_http_response_code: 301
  http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1
    X-Frame-Options: deny

- url: /ads.txt
  static_files: www/ads.txt
  upload: www/ads.txt
  secure: always
  redirect_http_response_code: 301
  http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1
    X-Frame-Options: deny

# file with extensions (longer cache period)
- url: /(.*\.(css|js|woff|woff2|ico|png|jpg|ico|mp4))
  static_files: www/\1
  upload: www/(.*)
  expiration: "14d"

# file with extensions
- url: /(.*\..*)
  static_files: www/\1
  upload: www/(.*)
  secure: always
  redirect_http_response_code: 301
  http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1
    X-Frame-Options: deny

# assume file without extensions use index.html
- url: /(.*)/
  static_files: www/\1/index.html
  upload: www/(.*)/index.html
  secure: always
  redirect_http_response_code: 301
  http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1
    X-Frame-Options: deny

- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always
  redirect_http_response_code: 301
  http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1
    X-Frame-Options: deny