apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-backend-canary
  name: employee-backend-canary
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    load-balancer-employee-backend-canary: "true"
  sessionAffinity: None
  type: ClusterIP
