apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-frontend-canary
  name: employee-frontend-canary
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    load-balancer-employee-frontend-canary: "true"
  sessionAffinity: None
  type: LoadBalancer
